### ISSUE TITLE
token error

### ISSUE THREAD

**Issue by itdpong** [harryho/vue2crm#1]
I see the following success message, but those url are not functional, and return this error in the admin page, would you pls give me some hints on how to setup the token db records???
 \{^_^}/ hi!

 Loading db.json
 Done

 Resources
 http://localhost:5354/token
 http://localhost:5354/customers
 http://localhost:5354/orders
 http://localhost:5354/products
 http://localhost:5354/categories

 Home
 http://localhost:5354

---------------------------------------------------------
LOGIN
{ "config": { "0": "username=hho@test.com&password=password", "transformRequest": {}, "transformResponse": {}, "timeout": false, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "headers": { "Accept": "application/json, text/plain, */*" }, "baseURL": "http://localhost:5354/", "params": {}, "method": "get", "url": "http://localhost:5354/token" }, "request": {} }

**Comment by harryho** [comment]
The back-end API is a fake Restful service for development purpose. It is supposed to setup without any coding. After you launch the json-server, you should be able to access the token via browser as below. There is no validation on credentials. 

![image](https://user-images.githubusercontent.com/2114456/31124238-45b178ba-a88f-11e7-8e73-1dd8b1df2b78.png)

I just test the code again, but I have no any clue about your problem. If you can explain how to replicate the issue, I will look into it.

**Comment by itdpong** [comment]
![err](https://user-images.githubusercontent.com/1797326/31165681-8ad1bbb4-a91e-11e7-9793-0c4a1154f905.JPG)

I remove the project and clone again, but it still fail.

should I create a 'server' folder inside vue2crm folder by myself????
and the 'npm install -g json-server'should execute inside the server folder????
is it accessable if I access http://localhost:5354  by chrome???

**Comment by harryho** [comment]
The screenshot on my comment is the chrome. I guess your problem is you haven't added **localhost** to your local host file. 

https://support.rackspace.com/how-to/modify-your-hosts-file/

Follow the instructions from the above link to open your host file. Add **localhost** to the end of host file as below. It should work after that.

```
127.0.0.1 localhost
::1 localhost
```

**Comment by itdpong** [comment]
thank you so much, finally I make it works. Port 5354 already in use in my pc. I change the port number and then everythings ok
