### ISSUE TITLE
CORS misconfigured in backend-api.ts

### ISSUE THREAD

**Issue by IlyaSemenov** [harryho/vue2crm#12]
https://github.com/harryho/vue-crm/blob/406e3d2f6b4aa31edd29c5d4e012528054cb038d/src/utils/backend-api.ts#L19

This is plain wrong, Access-Control-Allow-Origin is a *response* header, not a *request* header. You should simply remove that line, it serves no purpose.

When used as a request header, Access-Control-Allow-Origin:
a) makes no good (and no sense);
b) breaks CORS (unless the CORS server is explicitly configured to allow it with Access-Control-Allow-Headers), with a message like this: *"Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response."*

**Comment by harryho** [comment]
Thanks for pointing out the flaws. But next time if you want to contribute to open project, please take some time to play around the project first. The file you commented has been stopped maintaining over 2 years. No any program refers to this obsolete file. I left this file is just for other who may want to build the real api call without code from the scratch.
