### ISSUE TITLE
Bad code in backend-api.ts

### ISSUE THREAD

**Issue by IlyaSemenov** [harryho/vue2crm#13]
https://github.com/harryho/vue-crm/blob/406e3d2f6b4aa31edd29c5d4e012528054cb038d/src/utils/backend-api.ts#L5-L6

https://github.com/harryho/vue-crm/blob/406e3d2f6b4aa31edd29c5d4e012528054cb038d/src/utils/backend-api.ts#L42-L51

There are obvious flaws:

1) It could be `let url = API_URL`. No point in using templating without the actual template.
2) It could be `return instance.post(API_URL + url, data)`. No point in creating an extra variable for single use.
3) It could be `return instance.post(url, data)`. No point in concatenating with API_URL because it's provided as instance's baseURL anyway.

Then, honestly, the whole wrapper doesn't really make much sense. Each of Axios request methods is simply re-exposed, it doesn't give any benefit over simply exposing a plain Axios instance.

**Comment by harryho** [comment]
Thanks for pointing out the flaws. But next time if you want to contribute to open project, please take some time to play around the project first. The file you commented has been stopped maintaining over 2 years. No any program refers to this obsolete file. I left this file is just for other who may want to build the real api call without code from the scratch.
