### ISSUE TITLE
Adding environment variables

### ISSUE THREAD

**Issue by afshin2003** [harryho/vue2crm#19]
Hi,
It seems that config/dev.env.js or config/prod.env.js is not used for adding environment variables anymore! Is my understanding true? Am I supposed to use chainWebpack in vue.config.js to add them?

BEST
Afshin

**Comment by harryho** [comment]
Hi Afshin,
Thanks for telling me your thoughts. Franky, i haven't worked on this repo for quite a while. I totally forgot what I did, LOL. It's just a pet project. Don't be too serious. Please feel free to update what you need. 
Cheers,Harry

Sent from Yahoo Mail on Android 
 
  On Wed, 17 Feb 2021 at 9:30 pm, Afshin<notifications@github.com> wrote:   


Hi,
It seems that config/dev.env.js or config/prod.env.js is not used for adding environment variables anymore! Is my understanding true? Am I supposed to use chainWebpack in vue.config.js to add them?

BEST
Afshin
