### ISSUE TITLE
json-server requires at least version 4 of Node, please upgrade

### ISSUE THREAD

**Issue by JPaulMora** [harryho/vue2crm#3]
Hi, I'm using node v10.0.0 and running `node build dev` fails with:

````
json-server requires at least version 4 of Node, please upgrade
[0] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[0] npm ERR! vue2crm@1.7.6 start:server: `json-server -p 5354 db/db.json`
[0] npm ERR! Exit status 1
npm ERR!
[0] npm ERR! Failed at the vue2crm@1.7.6 start:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````

Well, it seems it works with node v8.0.0.. for anyone reading this, install NVM and `nvm install 8.0.0`

**Comment by harryho** [comment]
Hi, I am going to close this issue, since I don't see anything which I need to follow up. Thanks for sharing.

**Comment by gildniy** [comment]
@JPaulMora Thanks the downgrade to v8 works!

**Comment by JPaulMora** [comment]
yeah thanks @harryho, solved it right when I was posting, still did so people could see.
