### ISSUE TITLE
login issue due to port in use

### ISSUE THREAD

**Issue by pinchysalt** [harryho/vue2crm#5]
I've installed and run Vue2CRM with this:
npm install --from-lock-file
npm run dev

I'm getting the login screen, and logging in with the default admin / password returns this:

Vue-CRM
User ID
email
admin@test.com
Password
password
••••••••
{ "config": { "0": "username=admin@test.com&password=password", "transformRequest": {}, "transformResponse": {}, "timeout": false, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "headers": { "Accept": "application/json, text/plain, */*" }, "baseURL": "http://localhost:5354/", "params": {}, "method": "get", "url": "http://localhost:5354/token" }, "request": {} }

**Comment by harryho** [comment]
Hi, @pinchysalt  
Could you please explain your issue in detail? e.g. You need to explain the context about what you are doing, and explain how to replicate your issue step by step. Anything you have tried but failed could be very helpful as well.

**Comment by pinchysalt** [comment]
I am evaluating this CRM for a project I'm starting an I'm tying to get the Vue-CRM application running on my local machine. I've downloaded the project and followed the steps below. When I execute the command "npm -run dev", the server starts and the login page comes up in my browser. The default user and password are already filled in. When I click the "login" button, I get a small black window appearing above the user name text field that contains the text in my previous post. 

The steps below are how I get the message

1) Clone project
git clone https://github.com/harryho/vue2crm.git
2) install dependences for Vue 2 CRM
cd vue2crm
npm install --from-lock-file
3) start the server with hot reload at localhost:8080
npm run dev
4) click "login"

The chrome console contains this info below:

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
webpack-internal:///27:18 token null
:5354/token:1 Failed to load resource: net::ERR_CONNECTION_RESET
webpack-internal:///27:34 Object
webpack-internal:///50:18 Error: Network Error
    at createError (webpack-internal:///76:16)
    at XMLHttpRequest.handleError (webpack-internal:///73:87)
webpack-internal:///269:23 login Error: Network Error
    at createError (webpack-internal:///76:16)
    at XMLHttpRequest.handleError (webpack-internal:///73:87)
webpack-internal:///265:68 loggedIn false
webpack-internal:///2:592 [Vue warn]: Property or method "timeout" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Login> at C:\Projects\vue2crm-master\src\components\Login.vue
       <VApp>
         <App> at C:\Projects\vue2crm-master\src\App.vue
           <Root>
warn @ webpack-internal:///2:592
2webpack-internal:///2:592 [Vue warn]: Property or method "mode" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Login> at C:\Projects\vue2crm-master\src\components\Login.vue
       <VApp>
         <App> at C:\Projects\vue2crm-master\src\App.vue
           <Root>
warn @ webpack-internal:///2:592

**Comment by harryho** [comment]
Hi @pinchysalt ,

I followed all steps from the README to get the app up again, and I am sure it is working in my environment. A quick guess, you didn't launch the backend API server successfully. If you launched the backend API successfully you should be able to see the sth as below.

```
##[1] > node build/dev-server.js
##[1]
##[0]
##[0]   \{^_^}/ hi!
##[0]
##[0]   Loading db/db.json
##[0]   Done
##[0]
##[0]   Resources
##[0]   http://localhost:5354/token
##[0]   http://localhost:5354/customers
##[0]   http://localhost:5354/orders
##[0]   http://localhost:5354/products
##[0]   http://localhost:5354/categories
```
It means you should be able to access the backend API via the browser. If you can't see anything from the terminal or console as above, obviously you haven't launched the backend API. I guessed the version of nodejs is 10.x or upper, please remove it and reinstall the LTS version nodejs 8.x. Give a go. Good luck.

**Comment by pinchysalt** [comment]
I installed nodejs 8.11.3 and got the same result above.
C:\Projects\vue2crm-master>npm run dev

> vue2crm@1.7.7 dev C:\Projects\vue2crm-master
> concurrently --kill-others "npm run start:server" "npm run start"

[0]
[0] > vue2crm@1.7.7 start:server C:\Projects\vue2crm-master
[0] > json-server -p 5354 db/db.json
[0]
[1]
[1] > vue2crm@1.7.7 start C:\Projects\vue2crm-master
[1] > node build/dev-server.js
[1]
[0]
[0]   \{^_^}/ hi!
[0]
[0]   Loading db/db.json
[0]   Done
[0]
[0]   Resources
[0]   http://localhost:5354/token
[0]   http://localhost:5354/customers
[0]   http://localhost:5354/orders
[0]   http://localhost:5354/products
[0]   http://localhost:5354/categories
[0]
[0]   Home
[0]   http://localhost:5354
[0]
[0]   Type s + enter at any time to create a snapshot of the database
[1] > Starting dev server...
[1]  DONE  Compiled successfully in 100203ms21:16:53
[1]
[1] > Listening at http://localhost:8080
[1]


====================
I've seen network errors from CORS before. It might have something to do with this error shown in the chrome console:
webpack-internal:///27:18 token null
:5354/token:1 Failed to load resource: net::ERR_CONNECTION_RESET
webpack-internal:///27:34 Object
webpack-internal:///50:18 Error: Network Error
at createError (webpack-internal:///76:16)
at XMLHttpRequest.handleError (webpack-internal:///73:87)
webpack-internal:///269:23 login Error: Network Error
at createError (webpack-internal:///76:16)
at XMLHttpRequest.handleError (webpack-internal:///73:87)
webpack-internal:///265:68 loggedIn false

**Comment by harryho** [comment]
Hi @pinchysalt , it seems you have the same issue someone already encountered before, it is possible the port 5354 has been used by another application in your environment. You can take a look the old issue: #1 

You can use following commands (Windows only)  to check after you stop the server.

```
netstat -ano | find ":5354" 
for /f "tokens=5" %p in ( 'netstat -ano ^| find ":5354"') do @(     
    for /f "tokens=1" %s in ( 'tasklist /fi "pid eq %p" ^| find "%p"') do @(
        echo PID:%p -- APP: %s
    ) 
)
```
good luck

**Comment by pinchysalt** [comment]
Thanks!!! AppleMobileDeviceService and Bonjour service were taking up my ports.
I'm running locally and can now see how I might be able to use Vue2CRM for my project. Very Excited!
