### ISSUE TITLE
Where is the backend code going?

### ISSUE THREAD

**Issue by brizer** [harryho/vue2crm#7]
Where is the backend code going?

**Comment by harryho** [comment]
Hey, i'm not sure what issue you want me to address. If you have any problem to get the project up and run, please explain the issue you are facing and how to replicate your issue step by step. I'm going to close your ticket. Please feel free to reopen it or submit another one.

**Comment by harryho** [comment]
Hey, i'm not sure what issue you want me to address. If you have any problem to get the project up and run, please explain the issue you are facing and how to replicate your issue step by step. I'm going to close your ticket. Please feel free to reopen it or submit another one.
